### PR TITLE
Register all kernels in one plugin

### LINKED ISSUE #106: xhr is called synchronously
## Description

`getJson` helper is using `XMLHttpRequest` synchronously, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Synchronous_and_Asynchronous_Requests#synchronous_request) and does not work well with service worker. Is there any technical season to avoid async call here or can we convert this function to use `fetch`?

https://github.com/jupyterlite/xeus/blob/6504866ceb6b89000f3786f59dcb2e343bfb88c0/src/index.ts#L15-L20

### PR DESCRIPTION
**Pull request by trungleduc**
Closes #106

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -13,36 +13,56 @@ import { IKernel, IKernelSpecs } from '@jupyterlite/kernel';
...
-    requires: [IKernelSpecs],
-    optional: [IServiceWorkerManager, IBroadcastChannelWrapper],
-    activate: (
-      app: JupyterLiteServer,
-      kernelspecs: IKernelSpecs,
-      serviceWorker?: IServiceWorkerManager,
-      broadcastChannel?: IBroadcastChannelWrapper
-    ) => {
+const kernelPlugin: JupyterLiteServerPlugin<void> = {
+  id: '@jupyterlite/xeus-kernel:register',
```
Comment (jtpio) [inline src/index.ts:41]: Looks like having a single plugin would prevent disabling some kernels via `disabledExtensions`?

Comment (trungleduc) [reply src/index.ts:41]: We can keep the current behavior by checking for the `PageConfig.disabledExtensions` value in the activation function?

Comment (trungleduc) [reply src/index.ts:41]: The reason we need synchronous XHR is to generate JupyterLab plugins dynamically from the fetch data. Which I do not feel is necessary since these plugins do not provide any token. If it's just about to disable some kernels later, we can have other mechanisms

Comment (jtpio) [reply src/index.ts:41]: Right, it would be great to remove this synchronous XHR.

Comment (martinRenou) [reply src/index.ts:41]: Do we really need the ability to disable kernels?

If users don't want a kernel in the UI, their solution is to not install it in the provided `environment.yml` file.

**Comment by trungleduc** [comment]
This PR is ready but i think it's safer to release it in a major version

**Review by martinRenou — APPROVED** [review]
Thanks!
